### ISSUE TITLE
可否自定义提示字段？

### ISSUE THREAD

**Issue by ghost** [ExcellentJR/vue-ace-editor#1]
请问编辑器有实时填充自定义的提示字段的接口吗？

**Comment by ExcellentJR** [comment]
我之前有做过把自己数据库中的表名导入提示的功能，在这个编辑器的demo里面好像没做这块，自己研究一下，应该不难的

**Comment by ExcellentJR** [comment]
@jiaqizhang77 我刚看了一下我之前的代码，是可以自定义的，API接口也是有的，只不过我当时组织的方式和这个demo里不一样，当时的方式很麻烦现在也不好直接列出来...你搜一下“ace-editor自定义提示”能搜到不少类似的博客，研究下

**Comment by ghost** [comment]
我用的是vue2-brace-editor，好像没有对应的接口，大神知道吗？我想修改vue2-brace-editor，但是修改之后不知道怎么打包，它的webpack文件没有input的配置，可以教教吗？怎么修改之后打包。

**Comment by ExcellentJR** [comment]
@jiaqizhang77 Fork出来一份代码，根据自己的需求去改，测试好了发布到npm上就可以通过npm install xxxx（xxxx是你取得包的名字）安装使用了

**Comment by jiaqizhang77** [comment]
好的，谢谢啊。我百度看看，第一次搞。

**Comment by ghost** [comment]
@ExcellentJR 好的，谢谢啊。我百度看看，第一次搞。

**Comment by ExcellentJR** [comment]
@jiaqizhang77 直接百度“npm包的发布”，教程很多的，需要注册一个npm的账号，另外关于测试可以搜一下“npm包不发布直接测试”看看相关文章

**Comment by ghost** [comment]
@ExcellentJR  那个需要打包成min文件，但是我看了里面webpack配置，都不知道怎么打包。尴尬，如果有时间可以帮忙看看 vue2-brace-editor包吗？

**Comment by ExcellentJR** [comment]
@jiaqizhang77 你先自己研究下吧，我现在项目上有些任务也需要研究下，我有时间看下...

**Comment by ghost** [comment]
@ExcellentJR 好的，非常感谢，就是这个自定义提示字段。
